### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by SaadBazaz** [konstaui/konsta#102]
### Clear and concise description of the problem

Something like this: https://framework7.io/docs/searchbar

Really essential in most apps.

### Suggested solution

Wrapping Framework 7's searchbar.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [x] I'm willing to open a PR

**Comment by ak4zh** [comment]
Framework7 also has an `AutoComplete` component for a select tag which allows user input. Hope that gets added as well.

**Comment by SaadBazaz** [comment]
I made this with Konsta. Do y'all think it's good enough?

https://user-images.githubusercontent.com/51885228/205429624-3acb40fa-0205-4cf2-9204-24db49cb01b1.mov

**Comment by nolimits4web** [comment]
available in 3.0.0
