### ISSUE TITLE
Use the direction attribute / Support RTL

### ISSUE THREAD

**Issue by omar2205** [konstaui/konsta#104]
### Clear and concise description of the problem

If we set the element's dir it should change the layout.

![image](https://user-images.githubusercontent.com/1373867/206658693-e657c291-4808-4563-a44d-49b0cc87604b.png)

But setting html attribute `dir = 'rtl'` or CSS `direction: rtl;`:

![image](https://user-images.githubusercontent.com/1373867/206658735-4a831af7-0558-484f-9f1b-fec25862770c.png)

### Suggested solution

 Add dir support for components

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by ibilux** [comment]
Just today I was hit with this news about RTL and that it is not supported yet in Konsta.
Most of the components support RTL already. So it won't be a lot of work I think.

**Comment by ibilux** [comment]
@omar2205 RTL is working now. Just wait for the next release.

**Comment by omar2205** [comment]
@ibilux Thanks!
