### ISSUE TITLE
Add script for running on mobile devices 

### ISSUE THREAD

**Issue by ollydixon** [konstaui/konsta#110]
### Clear and concise description of the problem

The premise of the library is "Mobile UI components" except there are no docs on how to run it on mobile.

### Suggested solution

Add a script to run each kitchen on a native device, simulator or emulator.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by ollydixon** [comment]
For example the command ``ionic serve`` returns ``Sorry! ionic serve can only be run in an Ionic project directory.```

**Comment by ollydixon** [comment]
Another example:

```
konsta % npx cap add ios
npm ERR! could not determine executable to run
```

How do we run this mobile components library on mobile?

**Comment by nolimits4web** [comment]
Konsta UI is a UI components ONLY library, it doesn't have page transitions, router or anything related to native mobile development. For this purpose it is recommended to use it with Ionic or Framework7
