### ISSUE TITLE
Transitions don't work with iOS & Capactor

### ISSUE THREAD

**Issue by ollydixon** [konstaui/konsta#111]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/ollydixon/konsta

### Bug description

When running on actual device transitions don't work.
Cannot swipe back on iOS or Android (video attached)

When going backwards there is no transition, it's just instant.

https://user-images.githubusercontent.com/6940726/208990469-f7f272b9-bb5c-4e52-9f91-7ae1a5e894a9.mov

### Expected Behavior

- When going backwards it should animate backwards
- When swiping it should swipe back

### Actual Behavior

Nothing happens. 
Makes the library incompatible for production as users expect native transitions and functionality.

### Konsta UI version

v1.0.2

### Platform/Target and Browser Versions

iPhone with Capacitor 6

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Konsta UI is a UI components ONLY library, it doesn't have page transitions, router or anything related to native mobile development. For this purpose it is recommended to use it with Ionic or Framework7
