### ISSUE TITLE
Type definitions broken

### ISSUE THREAD

**Issue by rollingmoai** [konstaui/konsta#144]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Import `konsta/react` on a TypeScript file

### Bug description

![image](https://github.com/konstaui/konsta/assets/75471378/40b7b45c-c177-4827-8d71-fa28c458fe05)

### Expected Behavior

Importing `konsta/react` works

### Actual Behavior

Importing `konsta/react` doesn't work

### Konsta UI version

2.0.0

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by 343max** [comment]
setting it to `none` creates a different error:

`Value is not accepted. Valid values: "Classic", "Node", "Node16", "NodeNext", "Bundler".`
