### ISSUE TITLE
3.0.0 publication on NPM issue

### ISSUE THREAD

**Issue by thehackermonkey** [konstaui/konsta#165]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.npmjs.com/package/konsta?activeTab=code

### Bug description

For some reason latest published version of Konsta has an extra `config` folder that breaks the functionality of the package. I downloaded and build the code  locally and there is no extra config folder so I think this is an issue with the npm publishing process.

### Expected Behavior

The published package should not have this extra folder: `/konsta/config/config /`
It should be: `/konsta/config/` 

### Actual Behavior

There is an extra config folder `/konsta/config/config /`

### Konsta UI version

3.0.0

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by OyewoleOyedeji** [comment]
I also have the same issue, running Manjaro with Node 20.5.1

**Comment by Jayke770** [comment]
Use this for the mean time.. I also encounter this error using react

`$ npm install`
`$ cd node_modules/konsta`
`$ cp config/config/* config/.`

**Comment by thehackermonkey** [comment]
> Use this for the mean time.. I also encounter this error using react
> 
> `$ npm install` `$ cd node_modules/konsta` `$ cp config/config/* config/.`

yeah, did the hack to work for the moment. But this will affect anyone installing from npm. Hope they check the issue soon.

**Comment by r-nl** [comment]
This is a decently major issue, just spent two hours debugging a project only to realize the project itself is broken. Will pin the version at 2 for now for stability.

**Comment by nolimits4web** [comment]
fixed in 3.0.1
