### ISSUE TITLE
Feature Request: Data Table Component from Framework7

### ISSUE THREAD

**Issue by D-Marc1** [konstaui/konsta#168]
### Clear and concise description of the problem

The data table component from Framework7 is amazing. Is there any way this could be ported over to Konsta UI?

### Suggested solution

Having the awesome Framework7 data table component ported over to Konsta UI

### Alternative

Using Framework7

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Released in latest updates
