### ISSUE TITLE
iOS dividers on a List are not showing up

### ISSUE THREAD

**Issue by daniromome** [konstaui/konsta#171]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/konsta-svelte?file=App.svelte

### Bug description

iOS dividers on a List are not showing up

### Expected Behavior

iOS dividers on a List are should show up

### Actual Behavior

iOS dividers on a List are not showing up, if you switch the App's theme to material and then to ios again they show up

### Konsta UI version

3.0.1

### Platform/Target and Browser Versions

iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Demo you provided uses Konsta 1.x
