### ISSUE TITLE
Scroll Position Bug in Examples.

### ISSUE THREAD

**Issue by aadrian** [konstaui/konsta#178]
Hi,

In the official examples (on any platform) when scrolling the main list, viewing an example and returning back, the scroll position is forgotten all the time (so one returns to the top of the list all the time :( ) .

Those examples are the main reason one would decide to use the library. 

Is it possible to fix it?

Thank you.

**Comment by nolimits4web** [comment]
Konsta is a components library, what you mention is not its reponsibility
