### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by Kevinsillo** [konstaui/konsta#196]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://stackblitz.com/edit/konsta-vue-pdrwdq?file=main.js

### Bug description

When I use k-list-input, you can see an error type in console.

```
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at use-theme-classes.js?v=82131380:48:25
    at ReactiveEffect.fn (chunk-ESTIRR4N.js?v=82131380:1235:13)
    at ReactiveEffect.run (chunk-ESTIRR4N.js?v=82131380:429:19)
    at get value (chunk-ESTIRR4N.js?v=82131380:1246:64)
    at triggerComputed (chunk-ESTIRR4N.js?v=82131380:448:20)
    at get dirty (chunk-ESTIRR4N.js?v=82131380:401:11)
    at instance.update (chunk-ESTIRR4N.js?v=82131380:7570:19)
    at callWithErrorHandling (chunk-ESTIRR4N.js?v=82131380:1650:32)
    at flushJobs (chunk-ESTIRR4N.js?v=82131380:1857:9)
```

### Konsta UI version

3.1.2

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Awolwe** [comment]
Same problem

**Comment by Awolwe** [comment]
if i fix with redacting just adding ?. 
    let theme = context?.value?.theme || 'ios';
here will be also problem
  if (!context.value.dark) return '';

**Comment by nolimits4web** [comment]
t0ggles-create konsta

**Comment by nolimits4web** [comment]
t0ggles-create konsta

**Comment by nolimits4web** [comment]
t0ggles-create konsta
