### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by joshua1** [konstaui/konsta#2]
Hi @nolimits4web How can i help/ contribute to getting out a svelte version . I see there is currently only react version in the source. I thought i could mix tailwind styling with framework 7 component's given that each component exports a className property , but that didn't seem to take any effect. I happened upon this project while searching for a way to do that.

**Comment by digitalnomad91** [comment]
Any updates on this? I'd be happy to help with this as well.

**Comment by gustavopch** [comment]
The README and website both mention Svelte support, but there's no branch where it's being worked on. 🤔

**Comment by digitalnomad91** [comment]
> The README and website both mention Svelte support, but there's no branch where it's being worked on. 🤔

Yep, the author doesn't seem to care either. Quite unfortunate...

**Comment by nolimits4web** [comment]
Svelte support will be added in January

**Comment by nolimits4web** [comment]
https://konstaui.com/svelte
