### ISSUE TITLE
Where the form input components/documentation for react

### ISSUE THREAD

**Issue by robhicks** [konstaui/konsta#202]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://konstaui.com/react

### Bug description

Form Inputs appear in the React kitchen sink app but not in the documentation

### Expected Behavior

They should appear in the documentation

### Actual Behavior

The form input components show up in the kitchen sink app but do not show up in the documentationl

### Konsta UI version

3.1.3

### Platform/Target and Browser Versions

latest chrome on IOS and android

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
No questions in issues
