### ISSUE TITLE
When click on dark them on website make dark theme in all browser

### ISSUE THREAD

**Issue by armbull** [konstaui/konsta#205]
### Clear and concise description of the problem

When click on dark theme on website make dark theme in all browser

when i click dark theme there is only dark theme in mobile, but when go to table section there is also white scroll bars
<img width="392" alt="Снимок экрана 2024-04-23 в 00 19 01" src="https://github.com/konstaui/konsta/assets/9640387/ef935d75-f69e-4b11-a6b6-84c3f6c5569c">

### Suggested solution

add on switch for dark theme css style
```css
:root {
  color-scheme: dark;
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You are free to add this rule into your app's css file
