### ISSUE TITLE
segmented-button getting red

### ISSUE THREAD

**Issue by Edsuns** [konstaui/konsta#30]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://konstaui.com/vue/segmented

### Bug description

Active segmented-button getting red.

![20220122180615](https://user-images.githubusercontent.com/59397432/150634384-11c60ff5-c4ee-4f75-94c8-53ab06a46d24.png)

### Expected Behavior

Active segmented-button is supposed to be white.

### Konsta UI version

0.7.0

### Platform/Target and Browser Versions

Windows 10 / Chrome 97.0.4692.71

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konstaui/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tailwind-mobile.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
fixed by #31
