### ISSUE TITLE
Svelte support will be added in January

### ISSUE THREAD

**Issue by joshua1** [konstaui/konsta#36]
@nolimits4web, any update on svelte ?
Svelte support will be added in January

_Originally posted by @nolimits4web in https://github.com/konstaui/konsta/issues/2#issuecomment-989826503_

**Comment by mkvillalobos** [comment]
Hi! Great work with KonstaUI.

Any update about KonstaUI Svelte release?  A projected release date?

Thank you so much for you work!

**Comment by nolimits4web** [comment]
Sorry guys, last months I have issues with health which I'm trying to resolve to be able to get back to work. As soon as I'm back, Svelte support is the number 1 thing on my todo list

**Comment by joshua1** [comment]
I wish you a speedy recovery @nolimits4web.

**Comment by MartinsOnuoha** [comment]
Recover well @nolimits4web , health's first. 🍵

**Comment by nolimits4web** [comment]
https://konstaui.com/svelte
