### ISSUE TITLE
Error on Svelte

### ISSUE THREAD

**Issue by JericoFX** [konstaui/konsta#46]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

cant

### Bug description

Cant bind a click event on svelte, just did a fresh install, cofigure tailwind like the page.
[image](https://prnt.sc/nxoKzDZ6ckJo)
Just to be sure i try both methods on:click={() => console.log("HI")} and the image one

### Expected Behavior

click event working

### Actual Behavior

error declaring the click event

### Konsta UI version

0.8.2

### Platform/Target and Browser Versions

windows, Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konstaui/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tailwind-mobile.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by JericoFX** [comment]
https://svelte.dev/repl/8ce26dcdc2dc43b193fde0f3452fc6f0?version=3.47.0 as you can see here the "hi" always launch no matter what y even try to surround the button with a div just to see if work and have the same result, and in my dev enviroment (is just the template from svelte with vite and tailwindcss) i have errors

**Comment by nolimits4web** [comment]
it must be `<Button onClick={() => console.log("HI")}>Click</Button>` instead
