### ISSUE TITLE
defaultValue for ListInputs in Svelte/Vue doesn't work

### ISSUE THREAD

**Issue by gevera** [konstaui/konsta#60]
### Clear and concise description of the problem

When using Konsta UI with Svelte or Vue and setting default values for inputs in ListInput via defaultValue, the inputs remain empty. See the documentation example:

```
    <ListInput
      label="Birthday"
      type="date"
      defaultValue="2014-04-30"
      placeholder="Please choose..."
    >
```

### Suggested solution

defaultValues should be set for inputs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Documentation is wrong here, will fix it. defaultValue used only in React as it is React specific feature. Use just `value` in Vue/Svelte

**Comment by gevera** [comment]
> Documentation is wrong here, will fix it. defaultValue used only in React as it is React specific feature. Use just `value` in Vue/Svelte

Thanks for reply. For some reason value in Svelte is not being set as well. I wish Konsta would support  regular Svelte bind:value . That way the defaults could be set when declaring the variables

**Comment by fredguth** [comment]
I can't make placeholder to work in `list input type="select"`. Are these problems related?
