### ISSUE TITLE
Support Ionic for Svelte

### ISSUE THREAD

**Issue by borgius** [konstaui/konsta#64]
### Clear and concise description of the problem

Looks like Ionic is supported for React and Vue, could you please add Ionic support for Svelte?

### Suggested solution

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is better to ask from Ionic team
