### ISSUE TITLE
on: click event on button does not work

### ISSUE THREAD

**Issue by formobi** [konstaui/konsta#71]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://stackblitz.com/edit/vite-fh6u6e
### Bug description

I tried adding simple increment count click handler on one of the buttons in Buttons.svelte
 ` let count = 0;
  function incrementCount() {
    count += 1;
  }
</script>

<Button on:click={incrementCount}>
        Button {count}
      </Button>
`
I get following error.

<Buttons> was created with unknown prop 'location' [Buttons.svelte:3578:92](http://localhost:3000/pages/Buttons.svelte?t=1660671636427)
<Buttons> was created with unknown prop 'navigate' [Buttons.svelte:3578:92](http://localhost:3000/pages/Buttons.svelte?t=1660671636427)

### Expected Behavior

counter should increment and should show on top of button.

### Actual Behavior

incremented counter not showing up on button.

### Konsta UI version

0.11.1

### Platform/Target and Browser Versions

chrome, firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by formobi** [comment]
https://github.com/formobi/sveltekit-konsta-capacitor

**Comment by nolimits4web** [comment]
This is expected, as you see on docs https://konstaui.com/svelte/button there is no any events, use `onClick` instead
