### ISSUE TITLE
iOS theme don't work in newer vite version 3.1.0 in dev mode

### ISSUE THREAD

**Issue by ibilux** [konstaui/konsta#74]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/sveltejs-kit-template-default-yznzfw

### Bug description

The iOS theme doesn't apply and won't show correctly in SvelteKit using newer vite version (`3.1.0-beta.1` and `3.1.0-beta.2`) in dev mode only (when runing `npm run dev`). But works in build version (`npm run preview`).
When reverting to vite `3.0.9` the iOS theme applies and works perfectly in both dev mode and preview mode.

I guess something changed in newer vite version:
https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md

### Expected Behavior

iOS theme

### Actual Behavior

Material theme

### Konsta UI version

v0.11.1

### Platform/Target and Browser Versions

Linux/Brave Version 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by JoshuaRileyDev** [comment]
I don't get any styles displaying when running Sveltekit, even with Vite v3.0.9, standard styled Tailwind HTML renders fine

**Comment by ibilux** [comment]
Reproduction link :

https://stackblitz.com/edit/sveltejs-kit-template-default-yznzfw

**Comment by ibilux** [comment]
The same bug still exist in v1.0.0-beta.5

**Comment by JoshuaRileyDev** [comment]
I've also got this bug with Vite v3.1.0

**Comment by ibilux** [comment]
> I've also got this bug with Vite v3.1.0

Bug is fixed in vite `v3.1.2`.
