### ISSUE TITLE
[React/Svelte/Vue] List Input and iOS theme: the class 'h-20' in inputClassName is overwritten by the class 'h-10'

### ISSUE THREAD

**Issue by DAnn2012** [konstaui/konsta#81]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://konstaui.com/react/list-input

### Bug description

List Input component and iOS theme: class 'h-20' in inputClassName is overwritten by class 'h-10'

### Expected Behavior

With the Material theme the class 'h-20' in inputClassName takes precedence over the class 'h-6' and the field is shown in the required height.

### Actual Behavior

![Schermata 2022-09-15 alle 16 39 22](https://user-images.githubusercontent.com/1197819/190435618-2381b370-4611-4519-be97-257e9efa7fae.png)

### Konsta UI version

1.0.1

### Platform/Target and Browser Versions

macOS Safari 16.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by rakanus** [comment]
can we validated in Svelte ?
as it seems issue still exist  
![CleanShot 2023-01-20 at 02 12 27](https://user-images.githubusercontent.com/27198873/213582997-de5add1d-41c9-4eec-9027-f1ff50398fa5.png)
![CleanShot 2023-01-20 at 02 13 55](https://user-images.githubusercontent.com/27198873/213583112-9ee96164-246f-4234-b728-b7e2ffa2b633.png)
