### ISSUE TITLE
Support type on Button

### ISSUE THREAD

**Issue by will-ks** [konstaui/konsta#82]
### Clear and concise description of the problem

As a developer using Konsta UI I want the `Button` component to support the same `type` property  as the `List Button` supports so that it can be used correctly in forms.

### Suggested solution

Copy `List Button`'s `type` implementation to `Button`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is already supported

**Comment by will-ks** [comment]
Hi @nolimits4web, thanks for the response, I just went ahead and tried it and it indeed correctly supported! The issue then is a TypeScript issue, as it's not included in the types definition for `Button` (at least in React).
<img width="933" alt="Screenshot 2022-09-16 at 11 52 11" src="https://user-images.githubusercontent.com/12501819/190612170-c6b8f8ca-fbec-45b0-adc6-66109d1e4e1d.png">

I can live with that though ;) Thanks!
