### ISSUE TITLE
Can not use framework7-icons in SvelteKit project

### ISSUE THREAD

**Issue by misog** [konstaui/konsta#91]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

Hello. When importing framework7-icon in new SvelteKit project with TailwindCSS in this code in `+layout.svelte`:
```
<script>
    import '../app.css';
    import { App, Icon, Tabbar, TabbarLink } from 'konsta/svelte';
    import { EnvelopeFill } from 'framework7-icons/svelte';
</script>
```

then VS code shows this error on the line with EnvelopeFill:
`Could not find a declaration file for module 'framework7-icons/svelte'. '/home/xxxxxxx/xxxxxxx/node_modules/framework7-icons/svelte/framework7-icons-svelte.js' implicitly has an 'any' type.`

Also Vite returns error 500 and console shows this:
```
Cannot use import statement outside a module
/home/xxxxxxx/xxxxxxx/node_modules/framework7-icons/svelte/framework7-icons-svelte.js:1
import Airplane from './svelte/Airplane.svelte';
```

### Expected Behavior

Framework7 icons should work.

### Konsta UI version

1.0.2

### Platform/Target and Browser Versions

Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by MarcGodard** [comment]
I am also having issues getting it to work on a basic svelte-kit project. I have a repo that is very basic if @nolimits4web would like access I can do that.
